config/routes.rb
Rails.application.routes.draw do

  get 'previous_course/show'

  post 'users/invite'

  get 'skills/edit', as: :edit_skills

  post 'skills/update', as: :update_skills

  get 'join_classes/index'
  post 'join_classes/join_courses'
  get 'notifications/polling', as: :notif_poll

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  get 'previous_course/show'
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :notifications, :only => [:index] do
  member do
    post :accept
    post :reject
    post :rate
    delete :mark_as_read
  end
  end

  devise_for :users
resources :users, :only => [:show, :edit] do
  member do
    post :rate
    get :show_skills
  end
end

   authenticated :user do
     root "home#index", as: "authenticated_root"
	end

  resources :courses do
    post 'edit_time_commitment', on: :member
    post 'join', on: :member
    post 'leave', on: :member
    post 'rate_members', on: :member
    get 'change_time_commitment'
    resources :teams do
      get 'join', on: :member
      post 'join_try', on: :member
      post 'express_interest', on: :member
      post 'add_github', on: :member
      delete 'leave', on: :member
    end
  end
  resources :teams
  resources :profile

	root "welcome#index"

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.mailbox.notifications.page params[:page] #.paginate(:page => params[:page], :per_page => 10)
  end
  
  def polling
   @num_notif = current_user.mailbox.notifications.count
     respond_to do |format|
   # format.html
    format.js
     end
  end

  def is_number? string
  true if Float(string) rescue false
end

  def rate
    alpha = 0.25
    notif = current_user.mailbox.notifications.where(id: params[:id]).first
    notif.mark_as_deleted(current_user)
    @user = User.find(params[:user_id])
    params[:skillset].each do |id, rating|
      if is_number?(id)
       @sr = SkillRating.where(skill_id: id.to_i, user_id: @user.id).first
      @sr.rating  = @sr.rating*(1-alpha) + rating.to_i*alpha
        @sr.reviews = @sr.reviews + 1
      @sr.save
       else
         if @user.dependability == 0
         @user.dependability = rating.to_i
         else
            @user.dependability =  @user.dependability*(1-alpha) + alpha*rating.to_i
         end
         @user.reviews = @user.reviews + 1
         @user.save
       end
      end
    flash[:notice] = "#{@user.first_name}'s ratings were updated based on your feedback!"
    notif.destroy
    redirect_to :back
  end

  def mark_as_read
   notif = current_user.mailbox.notifications.where(id: params[:id]).first
    @notif_id = params[:id]
    notif.destroy
     respond_to do |format|
    format.html
    format.js
  end
  end

  def accept
    notif = current_user.mailbox.notifications.where(id: params[:id]).first
    sender = notif.sender
    team = Team.find_by_id(notif.attachment.to_i) #team should exist, check that too
      if notif.notification_code.to_i == 1  #accept students offer to join team, you are the owner
         if (team.students.count < team.course.max_members) && (sender.find_course_team(team.course) == false )
           team.students.each { |st|
             if st.id.to_i != team.team_owner_id.to_i
             st.notify("SUCCESS", " #{sender.first_name} was successfully added to your team #{team.name}",nil,true,5,false,nil)
             end
             }
        TeamMembership.create(team_id: team.id, user_id: sender.id)
        #current_user.notify("SUCCESS","#{sender.first} was successfully added to your team #{team.name}",nil,true,5,false,nil)
           flash[:notice] = "#{sender.first_name} was successfully added to your team #{team.name}"
        sender.notify("SUCCESS", " You were accepted to the team #{team.name}",nil,true,5,false,nil)
           else
           flash[:notice] = "Your team was full or #{sender.first_name} is in another team"
           end
      elsif notif.notification_code.to_i == 3 #accept team owners invitation to join his team
           if (team.students.count < team.course.max_members) && (current_user.find_course_team(team.course) == false )
             team.students.each { |st|
             st.notify( "SUCCESS", "#{current_user.first_name} has accepted the invitation  to join team #{team.name}",nil,true,5,false,nil )
             }
        TeamMembership.create(team_id: team.id, user_id: current_user.id)
       # current_user.notify("SUCCESS","You were successfully added to the team #{team.name}",nil,true,5,false,nil)
         flash[:notice] ="You were successfully added to the team #{team.name}"
             #sender.notify("SUCCESS","#{current_user.first_name} has accepted the invitation  to join team #{team.name}",nil,true,5,false,nil)
             else
             flash[:notice] = "Team was full or you are already in another team"
           end
        end
    #notif.mark_as_deleted(current_user)
    notif.destroy
     redirect_to :back
  end

  def reject
    notif = current_user.mailbox.notifications.where(id: params[:id]).first
    sender = notif.sender
    team = Team.find_by_id(notif.attachment.to_i) #team should exist, check that too
    if notif.notification_code.to_i == 1 #reject students offer to join your team
     # current_user.notify("DENYING","#{sender.first} was denied permission to join your team #{team.name}",nil,true,6,false,nil)
      sender.notify("DENIED", "You were rejected from the team #{team.name}",nil,true,6,false,nil)
      flash[:notice] = "#{sender.first_name} was denied permission to join your team #{team.name}"

    elsif notif.notification_code.to_i == 3 # reject teams invitation to join
      sender.notify("DENIED","#{current_user.first_name} has rejected your invitation  to join team #{team.name}",nil,true,6,false,nil)
      flash[:notice] = "You rejected invitation to join the team #{team.name}"
    end
    #notif.mark_as_deleted(current_user)
    notif.destroy
    redirect_to :back
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<% #cache("#{notification.id}-#{notification.updated_at}") do %>
<div class="row" id="row-<%=notification.id%>"%>
  <div class= "col-md-5"%>
  <% if notification.notification_code.to_i == 5 %>
<div class="panel panel-success">
  <% elsif notification.notification_code.to_i == 6 %>
  <div class="panel panel-warning">
    <% else %>
   <div class="panel panel-default">
     <% end %>
  <div class="panel-heading"> <%= notification.subject %></div>
  <div class="panel-body">
  <%= notification.body %>
    <% if notification.notification_code.to_i == 10 %>
    <% course = (Team.find_by_id(notification.attachment.to_i)).course %>
    <%= course.name %>
   <% rating_array = [['n00b',0],['Some Experience',1],['Experienced',2],['Pro',3]] %>
    <%= form_for(:skillset, url: {controller: 'notifications', action: 'rate', id: notification.id, user_id: notification.sender.id}) do |f| %>
    <% course.skills.each do |sk| %>
    <p>
      <%= f.label sk.name %>
      <%= f.select sk.id.to_i, rating_array %>
    </p>
     <% end %>
    <p>
    <%= f.label :dependability, 'Dependability' %>
    <%= f.number_field(:dependability, in: 1..10, step: 1) %>
      <b>Out of 10 points</b>
    </p>
    <%= f.submit 'Submit' , class: "btn btn-success"%>
<% end %>
    <% end %>


   </div>
   <div class="panel-footer">
  <% if notification.notification_code.to_i == 1 %>
     <div class="row ">
     <%= button_to 'Accept', accept_notification_path(notification), class: "btn btn-success" %>
     <%= button_to 'DENY', reject_notification_path(notification), class: "btn btn-danger" %>
     </div>
  <% elsif notification.notification_code.to_i == 3 %>
   <%= button_to 'Accept', accept_notification_path(notification), class: "btn btn-success" %>
     <%= button_to 'Reject', reject_notification_path(notification), class: "btn btn-danger" %>
     <% else %>
      <% if notification.notification_code.to_i != 10 %>
     <%= link_to 'Mark as Read', mark_as_read_notification_path(notification), method: :delete, class: "btn btn-success btn-sm", remote: true%>
  <% end %>
     <% end %>
   </div>
</div>
    </div>
  </div>
<% #end %>

app/views/notifications/index.html.erb
<%= render partial: "notification", collection: @notifications %>
<% paginate @notifications %>

app/views/notifications/mark_as_read.js.erb
$("#row-<%=@notif_id%>").hide();

app/views/notifications/polling.js.erb
$("#notif-count").html("<%= @num_notif %>");
<% if(@num_notif > 0) %>
$("#notif-count").show();
<% else %>
$("#notif-count").hide();
<% end %>