config/routes.rb
Rails.application.routes.draw do

  get 'previous_course/show'

  post 'users/invite'

  get 'skills/edit', as: :edit_skills

  post 'skills/update', as: :update_skills

  get 'join_classes/index'
  post 'join_classes/join_courses'
  get 'notifications/polling', as: :notif_poll

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  get 'previous_course/show'
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :notifications, :only => [:index] do
  member do
    post :accept
    post :reject
    post :rate
    delete :mark_as_read
  end
  end

  devise_for :users
resources :users, :only => [:show, :edit] do
  member do
    post :rate
    get :show_skills
  end
end

   authenticated :user do
     root "home#index", as: "authenticated_root"
	end

  resources :courses do
    post 'edit_time_commitment', on: :member
    post 'join', on: :member
    post 'leave', on: :member
    post 'rate_members', on: :member
    get 'change_time_commitment'
    resources :teams do
      get 'join', on: :member
      post 'join_try', on: :member
      post 'express_interest', on: :member
      post 'add_github', on: :member
      delete 'leave', on: :member
    end
  end
  resources :teams
  resources :profile

	root "welcome#index"

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!

  def rate_members
    course = Course.find(params[:id])
    Team.where(course_id: course.id).each {|t| t.send_rating_notif}
    flash[:notice] = "All students were asked to rate their teammates"
    redirect_to :back
  end

  def new
     @skills = Skill.all
    @course = Course.new
  end

  def change_time_commitment
    @course = Course.find(params[:course_id])
    respond_to do |format|
    format.html
    format.js
    end
  end

  def create
    @course = Course.new(course_params)
    @course.instructor_id = current_user.id
    if @course.save
      params[:skillset].each do |id, rating|
        puts rating.to_i
        if rating.to_i > 0
       CourseSkillset.create(course_id: @course.id, skill_id: id.to_i, min_rating: rating.to_i)
        end
    end
      flash[:notice] = "Course successfully created!"
      redirect_to course_path(@course)
    else
      render 'new'
    end
  end

  def edit
  end

  def edit_time_commitment
    course = Course.find(params[:id])
    enroll = Enrollment.where(user_id: current_user.id, course_id: course.id).first
    enroll.time_commitment = params[:time].to_i
    #if enroll.save
      #flash[:notice] = "Time Commitment updated successfully"
  #  else
    #  flash[:notice] = "Bad Time value supplied"
 #   end
    @time = params[:time]
      respond_to do |format|
    format.html
    format.js
  end
   # redirect_to :back
  end

  def join
    @course = Course.find(params[:id])
    Enrollment.create(course_id: @course.id.to_i, user_id: current_user.id, time_commitment: 2)
    flash[:notice] = "You were successfully added to the course"
    redirect_to :back
  end

  def leave
    @course = Course.find(params[:id])
    Enrollment.where(course_id: @course.id.to_i, user_id: current_user.id).first.destroy
    flash[:notice] = "You were removed from the course"
    redirect_to :back
  end

  def invite
    @user = User.find(params[:id])
    @team = Team.find_by_id(params[:team_id])
    # make notif
    recp = @user.notify("INVITE","asdf",nil,true,1,false,current_user)
    notif = @user.mailbox.notifications.where(id: recp.notification_id).first
    notif.attachment = @team.id
    notif.body =  "#{current_user.first_name} #{current_user.last_name} has invited you to join his team #{@team.name}!"
    notif.save
    flash[:notice] = "#{@user.first_name} was notified of your interest!"
    redirect_to :back
  end

  def show
    @course = Course.find(params[:id])
    @teams = @course.teams.page(params[:team_tab_page]).per(5)  
    @enrolled = false
    @instr = false
    inst = User.find_by_id(@course.instructor_id.to_i)
    if inst
      if inst.id == current_user.id
        @instr = true
      end
    end
    if current_user.courses.include?(@course)
    @enrolled = true
    @user_course_team = current_user.find_course_team(@course)
    @time = current_user.enrollments.where(course_id: @course.id).first.time_commitment
    end
    @ordered_students = @course.students 
    if(params[:order_skill].present?)
      students_ids = @ordered_students.collect{ |st| st.id }
      id = params[:order_skill]
      if id.to_i == -1 #order by time commitment
          ratings = Enrollment.where(course_id: @course.id).order(time_commitment: :desc)
      elsif id.to_i != -2
          ratings = SkillRating.where(skill_id: id).where("user_id IN (?)", students_ids).order(rating: :desc) #order by individual skills
      end
      if id.to_i == -2
        @ordered_students = @course.students.sort_by{|obj| obj.overall_rating(params[:id])}.reverse! 
      else
          @ordered_students = ratings.collect{|r| User.find(r.user_id)} 
      end
    end
    @ordered_students = Kaminari.paginate_array(@ordered_students).page(params[:classmate_tab_page]).per(15)
  end

  def course_params
    params.require(:course).permit(:name, :description, :max_members, :min_time_commitment, :start_date, :end_date)
  end

  def search

  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<tr>
  
</tr>

app/views/courses/_student.html.erb
<tr class="st">
  <% #cache(cache_key_for_student_row(student, current_course, show_team, current_team, current_team_owner_id)) do %>
  <td>
    <%= link_to "#{student.first_name} #{student.last_name} ", user_path(student), class: "st-name"%>
    <% if show_team %>
       <div class="popover-markup">
      <%= link_to '', show_skills_user_path(student, course_id: current_course.id), remote: true, class: "trigger", data: { placement: "auto" }%>
  <div class="head hide">
   <%= "#{student.first_name} #{student.last_name}" %>
   </div>
         <% end %>
  <div class="content hide">
    <div class="chart-container-<%=student.id%>" ></div>
  </div>
</div>
    <% if (show_team == false) && (student.id == current_team_owner_id)%>
    <span class="label label-warning">Owner</span>
    <% end %>
  </td>
  <td><%= student.year %> </td>
  <td><%= student.major %> </td>
  <% if show_team %>
  <td>
    <% tm = student.find_course_team(current_course) %>
    <% if !tm %>
    <%= 'Free' %>
    <% else %>
    <%= link_to tm.name, tm %>
    <% end %>
    <% if current_team != false && student.id != current_user.id && (tm == false || tm.id != current_team.id)%>
    <%= link_to users_invite_path(id: student.id, team_id: current_team.id), method: :post, class: "inv", style: "display: none;" do %>
    <span class="label label-default"> Invite </span>
    <% end %>
    <% end %>
  </td>
  <% end %>
  <% #end %>
</tr>

app/views/courses/_timecommit.html.erb
<%= form_tag(edit_time_commitment_course_path(@course), class:"col-md-8 pull-left", remote: true) do %>
<%= number_field_tag(:time, in: 1..20, step: 1) %>
<%= submit_tag("Update Time Commitment") %>
<% end %>

app/views/courses/change_time_commitment.js.erb
$('#update-form').html("<%= j (render 'timecommit') %>");
$('#update-form').slideDown(350);

app/views/courses/edit.html.erb
<h1>Courses#edit</h1>
<p>Find me in app/views/courses/edit.html.erb</p>

app/views/courses/edit_time_commitment.js.erb
$('#tc').html("<%= j ( "Your time commitment: #{@time} hrs/wk") %>");
$('#update-form').slideUp(350);

app/views/courses/index.html.erb
<h1>Courses#index</h1>
<p>Find me in app/views/courses/index.html.erb</p>

app/views/courses/new.html.erb
<% rating_array = [['n00b',0],['Some Experience',1],['Experienced',2],['Pro',3]] %>
<%= form_for(@course, url: courses_path) do |f| %>
<% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>
      <ul>
        <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, 'Name' %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="form-group">
  <%= f.label :description, 'Description' %><br />
  <%= f.text_area :description, autofocus: true %>
  </div>
  <div class="form-group">
  <%= f.label :max_members, 'Maximum number of students per Team' %><br />
  <%= f.number_field(:max_members, in: 1..10, step: 1) %>
  </div>
  <div class="form-group">
    <%= f.label :min_time_commitment, 'Minimum Time Commitment' %><br />
    <%= f.number_field(:min_time_commitment, in: 1..20, step: 1) %>
  </div>
 <div class="form-group">
   <%= f.label :start_date, 'Start Date' %><br />
   <%= f.date_select :start_date %>
  </div>
 <div class="form-group">
   <%= f.label :end_date, 'End Date' %><br />
   <%= f.date_select :end_date %>
  </div>
  <%= f.label :skillset %>
  <div class="row">
    <div class="form-group col-md-4" style="overflow-y: scroll;height: 200px;border: solid" >
      <%= fields_for(:skillset) do |field| %>
        <% Skill.all.each do |sk| %>
          <p>
          <%= field.label sk.name %>
          <%= field.select sk.id.to_i, rating_array  %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
  
<%= f.submit 'Create' %>
<% end %>

app/views/courses/show.html.erb
<!-- <h1>Courses#show</h1>
<p>Find me in app/views/courses/show.html.erb</p> -->
<%= javascript_tag do %>
$(document).ready(function(){
//alert("fuck");
$("#up_hd").hover(function(){
  $("#up_lnk").show();
}, function(){
$("#up_lnk").hide();
});
$(".st").hover(function(){
  $(this).find(".inv").show();
}, function(){
$(this).find(".inv").hide();
});
$(".st-name").hover(function(){
  $(this).parent().find(".trigger").trigger('click');
});
//$(".tem").hover(function(){
//  $(this).find("#express_interest").show();
//}, function(){
//$(this).find("#express_interest").hide();
//});
if(location.href.search("#teams") > -1)
{
 $("#classmates").removeClass('active in ');
 $("#c").removeClass("active");
  $("#t").addClass("active");
 $("#teams").addClass('active in');
}

$("#teams .pagination a").attr("href",function(n,v) {
  return v+"#teams";
});
 //$('#teams .pagination a').click(function() {
  //alert("fuck");
//});
$('.popover-markup > .trigger').popover({
    html : true,
    title: function() {
      return $(this).parent().find('.head').html();
    },
    content: function() {
      return $(this).parent().find('.content').html();
    },
    container: 'body'
});

});


<% end %>

<div class="row">
    <div class="col-md-4">
    <h1><%= @course.name %> </h1>
          <p><small><%= @course.description %></small> </p>
       <span class="label label-default"> <%= @course.max_members %> per team </span> &nbsp;
      <span class="label label-default"> <%= @course.min_time_commitment %> hrs/wk </span> &nbsp;
      <% @course.skills.each do |sk| %>
      <span class="label label-default"> <%= sk.name %> </span> &nbsp;
      <% end %>
      <p> </p>
      <% if !@enrolled %>
      <p>
      <%= link_to 'Join Class', join_course_path(@course), method: :post, class: "btn btn-primary", id: "joiner" %>
      </p>
      <% else %>
      <% if @user_course_team == false %>
        <p>
          <%= link_to 'Leave Class', leave_course_path(@course), method: :post, class: "btn btn-danger", id: "leaver" %>
      </p>
      <% else %>
      <p><small> Leave your team to leave the course </small></p>
      <% end %>
      <% end %>
      <% if @instr %>
      <%= link_to 'Rate Teammates', rate_members_course_path(@course), method: :post, class: "btn btn-success", id: "rater" %>
      <% end %>
  </div>

</div>
<% if @enrolled %>
<div class="row">
  <h5>
    <span id="up_hd">
  <span id="tc"><%= "Your time commitment: #{@time} hrs/wk" %></span>
  <%= link_to ' Update', course_change_time_commitment_path(@course), id: "up_lnk", remote: true, style: "display: none;" %>    </span>
 </h5>
   <div id="update-form" style="display:none;"></div>
<% end %>
</div>
<ul class="nav nav-tabs">
  <li id = "c" class="active"><a data-toggle="tab" href="#classmates">Classmates</a></li>
  <li id ="t"><a data-toggle="tab" href="#teams">Teams</a></li>
</ul>

<div class="tab-content">
  <div id="classmates" class="tab-pane fade in active">
    <h5>Order by </h5>
   <div class="btn-group">
     <% @course.skills.each do |skill| %>
    <%= link_to skill.name, course_path(@course,order_skill: skill.id) , class: "btn btn-sm btn-default" %>
    <% end %>
     <%= link_to 'Time', course_path(@course,order_skill: -1) , class: "btn btn-sm btn-default" %>
     <%= link_to 'OverallRating', course_path(@course,order_skill: -2) , class: "btn btn-sm btn-default" %>
     <br><br><br>
    </div>
      <% if @enrolled %>
    <table class="table table-hover">
      <tr>
        <th> Name </th>
        <th> Year </th>
        <th> Major </th>
        <th> Team </th>
     </tr>

      <%= render partial: "student", collection: @ordered_students, locals: {current_course: @course, show_team: true, current_team_owner_id: false , current_team: @user_course_team} %>

    </table>
    <%= paginate @ordered_students, param_name: :classmate_tab_page%>

<% else %>
        <h3> Enroll to view students </h3>
      <% end %>
  </div>

  <div id="teams" class="tab-pane fade">
    <% if @enrolled %>
    <%= render :partial => "teams/team", :collection => @teams, locals: {current_course: @course, user_course_team: @user_course_team} %>
    <%= paginate @teams, param_name: :team_tab_page%>

    <% if @user_course_team == false %>
    <div class="pull-left">
    <%= link_to 'Create a Team', new_course_team_path(@course) , class: "btn btn-primary"%>
    </div>
    <% end %>
  </div>
  <% else %>
  <h3> Enroll to view teams </h3>
  <% end %>
</div>