config/routes.rb
Rails.application.routes.draw do

  get 'previous_course/show'

  post 'users/invite'

  get 'skills/edit', as: :edit_skills

  post 'skills/update', as: :update_skills

  get 'join_classes/index'
  post 'join_classes/join_courses'
  get 'notifications/polling', as: :notif_poll

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  get 'previous_course/show'
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :notifications, :only => [:index] do
  member do
    post :accept
    post :reject
    post :rate
    delete :mark_as_read
  end
  end

  devise_for :users
resources :users, :only => [:show, :edit] do
  member do
    post :rate
    get :show_skills
  end
end

   authenticated :user do
     root "home#index", as: "authenticated_root"
	end

  resources :courses do
    post 'edit_time_commitment', on: :member
    post 'join', on: :member
    post 'leave', on: :member
    post 'rate_members', on: :member
    get 'change_time_commitment'
    resources :teams do
      get 'join', on: :member
      post 'join_try', on: :member
      post 'express_interest', on: :member
      post 'add_github', on: :member
      delete 'leave', on: :member
    end
  end
  resources :teams
  resources :profile

	root "welcome#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeamJam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% #cache("#{current_user.mailbox.notifications.count}-#{unread_messages_count}") do %>
  <header class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <style>
        .navbar { min-height:49px;   }
        .navbar .navbar-brand{ margin-left: -40px !important ;padding: 0 12px;font-size: 18px;line-height: 49px;height: 49px; }
        .navbar .navbar-nav > li > a {  padding-top: 0px; padding-bottom: 0px; line-height: 49px;}
        </style>

        <div id="logo" class="navbar-brand">
          <%= link_to(root_path) do %>
          <span style="color:white">Team<span style="color:red">JAM </span></span>
          <% end %>
        </div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
        	<% if user_signed_in? %>
          <script>
            $(document).ready(function() {

    setInterval(function () {
      $.ajax({
  url: '/notifications/polling',
  data: { },
  async: true,
  dataType: 'script'
});
    } , 5000);
});
          </script>
						<ul class="nav navbar-nav navbar-right" style="white-space: nowrap;">
              <% num_notif = current_user.mailbox.notifications.count %>
              <% if num_notif > 0 %>
                <li><%= link_to(notifications_path) do %>
                Notifications
                <span class="label label-danger" id="notif-count" style="display: none;"><%= num_notif %></span>
                <% end %>
              <% end %>
               </li>
              <li id="notif"><%= link_to mailbox_inbox_path do %>
                Messages
                <% if unread_messages_count > 0 %>
                <span class="label label-danger"><%=unread_messages_count%></span>
                <% end %>
                <% end %>
              </li>
              <li> <%= link_to 'My Profile', user_path(current_user) %> </li>
              <li> <%= link_to 'Create Course', new_course_path %> </li>
              <li> <%= link_to 'Join Course', {:controller => '/join_classes', :action => 'index'} %> </li>
              <li> <%= link_to 'Previous Course', {:controller => '/previous_course', :action => 'show'} %> </li>
              <li> <%= link_to 'Edit Account', edit_user_registration_path %></li>
               <li> <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
						</ul>
          <% end %>
        </nav>
      </div>
    </div>
  </header>
  <% #end %>
   <div id="wrapper">
 <div id="sidebar-wrapper">
     <% if user_signed_in? %>
    <% #cache(cache_key_course_team) do %>
              <ul class="sidebar-nav">
               <li class="sidebar-brand">
                        Your Classes
                </li>
              <% courses_app = current_user.courses.where("end_date > ?", DateTime.now) %>
             <% teams_app = current_user.teams %>
             <% course_team_app = Hash.new %>
             <% courses_app.each do |course| %>
                <% teams_app.each do |team|  %>
                 <%  if team.course == course  %>
                 <%  course_team_app[course] =  team  %>
                 <%  end  %>
              <%  end  %>
             <% end  %>
                <% courses_app.each do |course| %>
                  <% if course_team_app.has_key?(course) %>
                  <% team = course_team_app[course] %>
                        <li><%= link_to course.name, course %>
                            <ul>
                                <li><%= link_to team.name, team %>
                            </ul>
                        </li>
                   <% else %>
                      <li> <%= link_to course.name, course %></li>
                 <% end %>
              <% end %>
           <% end %>
      </ul>
   <% #end %>
  </div>

 <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">

		                    <% flash.each do |name, msg| %>
			                    <%= content_tag(:div, msg, class: "alert alert-info") %>
		                        <% end %>
				                      <%= yield %>
                      </div>
                </div>
            </div>
        </div>
  </div>
</body>
</html>